name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

  install:
    runs-on: ubuntu-latest

    needs: common

    steps:
      - name: Install dependencies
        run: npm install

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: node_modules

  build:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - name: Restore artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifacts

      - name: Build
        run: npm run build --if-present

    env:
      CI: true

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: npm test

    env:
      CI: true

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

    env:
      CI: true
