name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  setup:
    runs-on: ubuntu-latest

    needs: checkout

    steps:
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ runner.os }}

      - name: Build
        run: npm run build --if-present

      - name: Save build cache
        uses: actions/cache@v2
        with:
          path: build
          key: build-${{ runner.os }}

    env:
      CI: true

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

    env:
      CI: true

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

    env:
      CI: true
