name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  setup:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up shared workspace
        run: mv $GITHUB_WORKSPACE /shared-workspace
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Restore workspace
        run: mv /shared-workspace $GITHUB_WORKSPACE

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up shared workspace
        run: mv $GITHUB_WORKSPACE /shared-workspace
      - name: Running tests
        run: npm test
      - name: Restore workspace
        run: mv /shared-workspace $GITHUB_WORKSPACE

  deploy:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
